# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropetyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('profile_picture', models.ImageField(upload_to='profile_pic')),
                ('property_brochure', models.ImageField(upload_to='brochure')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
