# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200603_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propetyinfo',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='propetyinfo',
            name='city_name',
            field=models.CharField(default='Barrington', max_length=100),
            preserve_default=False,
        ),
    ]
