# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200603_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropetyInfo',
            new_name='PropertyInfo',
        ),
    ]
