# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200603_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
