# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-18 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('post', models.TextField()),
                ('date', models.DateField()),
                ('photo', models.ImageField(upload_to='news_pics')),
            ],
        ),
    ]
